extends RefCounted
class_name ActorFramework

const MessageTypesScript = preload("res://CoreEngine/Scripts/Contract/MessageTypes.gd")

const TYPE_ANY: StringName = MessageTypesScript.TYPE_ANY
const TYPE_LEVEL_EVENT_REQUEST: StringName = MessageTypesScript.TYPE_LEVEL_EVENT_REQUEST
const TYPE_LEVEL_EVENT: StringName = MessageTypesScript.TYPE_LEVEL_EVENT
const TYPE_PLAYER_DATA_CHANGED: StringName = MessageTypesScript.TYPE_PLAYER_DATA_CHANGED
const TYPE_SAVE_REQUEST: StringName = MessageTypesScript.TYPE_SAVE_REQUEST
const TYPE_SAVE_COMPLETED: StringName = MessageTypesScript.TYPE_SAVE_COMPLETED
const TYPE_LOAD_ROOM_REQUEST: StringName = MessageTypesScript.TYPE_LOAD_ROOM_REQUEST
const TYPE_LOAD_AREA_REQUEST: StringName = MessageTypesScript.TYPE_LOAD_AREA_REQUEST
const TYPE_RESET_MAP_STARTING_COORDS_REQUEST: StringName = MessageTypesScript.TYPE_RESET_MAP_STARTING_COORDS_REQUEST
const TYPE_SHIFT_PLAYER_REQUEST: StringName = MessageTypesScript.TYPE_SHIFT_PLAYER_REQUEST
const TYPE_SET_LOOP_TARGET: StringName = MessageTypesScript.TYPE_SET_LOOP_TARGET
const TYPE_CLEAR_LOOP_TARGET: StringName = MessageTypesScript.TYPE_CLEAR_LOOP_TARGET
const TYPE_BATTLE_RESULT_REQUEST: StringName = MessageTypesScript.TYPE_BATTLE_RESULT_REQUEST
const TYPE_ROOM_LOADED: StringName = MessageTypesScript.TYPE_ROOM_LOADED
const TYPE_AREA_LOADED: StringName = MessageTypesScript.TYPE_AREA_LOADED

const TYPE_INPUT_MODE_CHANGE_REQUEST: StringName = MessageTypesScript.TYPE_INPUT_MODE_CHANGE_REQUEST
const TYPE_INPUT_MODE_CHANGED: StringName = MessageTypesScript.TYPE_INPUT_MODE_CHANGED

const TYPE_APPLY_DAMAGE_REQUEST: StringName = MessageTypesScript.TYPE_APPLY_DAMAGE_REQUEST
const TYPE_DAMAGE_APPLIED: StringName = MessageTypesScript.TYPE_DAMAGE_APPLIED
const TYPE_COMBAT_SYNC_REQUEST: StringName = MessageTypesScript.TYPE_COMBAT_SYNC_REQUEST
const TYPE_COMBAT_STATE_CHANGED: StringName = MessageTypesScript.TYPE_COMBAT_STATE_CHANGED

const TYPE_ITEM_ACTION_REQUEST: StringName = MessageTypesScript.TYPE_ITEM_ACTION_REQUEST
const TYPE_INVENTORY_UPDATED: StringName = MessageTypesScript.TYPE_INVENTORY_UPDATED

const TYPE_QUEST_ACTION_REQUEST: StringName = MessageTypesScript.TYPE_QUEST_ACTION_REQUEST
const TYPE_QUEST_UPDATED: StringName = MessageTypesScript.TYPE_QUEST_UPDATED

const TYPE_DIALOGUE_ACTION_REQUEST: StringName = MessageTypesScript.TYPE_DIALOGUE_ACTION_REQUEST

const TYPE_AUDIO_REQUEST: StringName = MessageTypesScript.TYPE_AUDIO_REQUEST

const TYPE_ADD_GENERATED_ROOM: StringName = MessageTypesScript.TYPE_ADD_GENERATED_ROOM
const TYPE_CLEAR_GENERATED_ROOMS: StringName = MessageTypesScript.TYPE_CLEAR_GENERATED_ROOMS
const TYPE_RUNTIME_EVENT_SIGNAL: StringName = MessageTypesScript.TYPE_RUNTIME_EVENT_SIGNAL
const TYPE_RUNTIME_EVENT_START: StringName = MessageTypesScript.TYPE_RUNTIME_EVENT_START
const TYPE_RUNTIME_EVENT_ACTION: StringName = MessageTypesScript.TYPE_RUNTIME_EVENT_ACTION
